### ISSUE TITLE
import regionmask error

### ISSUE THREAD

**Issue by cccchou** [regionmask/regionmask#497]
when i type import regionmask it shows error:
>>> import regionmask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Anaconda\envs\cesm\lib\site-packages\regionmask\__init__.py", line 5, in <module>
    from . import core, defined_regions
  File "E:\Anaconda\envs\cesm\lib\site-packages\regionmask\defined_regions\__init__.py", line 3, in <module>
    from . import _natural_earth, _ressources
  File "E:\Anaconda\envs\cesm\lib\site-packages\regionmask\defined_regions\_natural_earth.py", line 14, in <module>
    from ..core.regions import Regions
  File "E:\Anaconda\envs\cesm\lib\site-packages\regionmask\core\regions.py", line 15, in <module>
    from .mask import _inject_mask_docstring, _mask_2D, _mask_3D
  File "E:\Anaconda\envs\cesm\lib\site-packages\regionmask\core\mask.py", line 8, in <module>
    from regionmask.core.coords import _get_coords
  File "E:\Anaconda\envs\cesm\lib\site-packages\regionmask\core\coords.py", line 4, in <module>
    import cf_xarray  # noqa: F401
  File "E:\Anaconda\envs\cesm\lib\site-packages\cf_xarray\__init__.py", line 2, in <module>
    from .accessor import CFAccessor  # noqa
  File "E:\Anaconda\envs\cesm\lib\site-packages\cf_xarray\accessor.py", line 29, in <module>
    from .criteria import (
  File "E:\Anaconda\envs\cesm\lib\site-packages\cf_xarray\criteria.py", line 17, in <module>
    cf_role_criteria: Mapping[str, Mapping[str, str]] = {
TypeError: 'ABCMeta' object is not subscriptable

**Comment by mathause** [comment]
Thanks for using regionmask! That is a "bug" in cf-xarray. The v0.8.5 of cf-xarray requires python 3.9+ but did not update `requires-python` version to  `= ">=3.9"`. So the solution is to install cf-xarray version 0.8.4 (using pip or mamba).
